export enum STEP_BALL_FORM_VALIDATION_STATUS_CODES {
  BALL_TITLE_TOO_SHORT= 410,
  BALL_HOST_TOO_SHORT= 420,
  VALID= 200,
  URL_INVALID= 430,
  END_DATE_BEFORE_START_DATE= 440,
  BALL_DESCRIPTION_TOO_SHORT= 450
}

export default STEP_BALL_FORM_VALIDATION_STATUS_CODES
